### ISSUE TITLE
Problem on running the install step

### ISSUE THREAD

**Issue by pedrobslisboa** [ml-in-barcelona/server-reason-react#111]
The document has the install step:
https://ml-in-barcelona.github.io/server-reason-react/local/server-reason-react/intro.html#install

But when running `opam install server-reason-react`

The following error appears:

[ERROR] No package named server-reason-react found.

Is it available at opam? Is the documentation right?

**Comment by davesnx** [comment]
It's currently not available in opam, and should be installed with a pin. Let me update the instructions.

```
opam pin add server-reason-react.dev "https://github.com/ml-in-barcelona/server-reason-react" -y
```

**Comment by davesnx** [comment]
Updated the documentation in https://github.com/ml-in-barcelona/server-reason-react/commit/dc38221e4de0ad21d209d855217c61fbfe46de6c

Thanks for reporting. Feel free to open as many issue as you find :D
