### ISSUE TITLE
Congrats on the project

### ISSUE THREAD

**Issue by pedrobslisboa** [ml-in-barcelona/server-reason-react#114]
I'm a huge fan of ReasonML, and the main issue that prevented me from continuing with some projects was the lack of native SSR. Rescript evolved into something quite different from ReasonML and OCaml, which was also frustrating for me.

I discovered this repository more than a year ago, and it reignited my motivation. And, to better understand how this repository and feature works, I created this project: https://github.com/pedrobslisboa/universal-portal

I plan to bring all my known issues here so that we can discuss them more thoroughly.

Congrats on the project.
See you.

**Comment by davesnx** [comment]
Thanks for those words, it made my day. The future of all of this is exciting.

Please feel free to open any issue that you encounter!

**Comment by pedrobslisboa** [comment]
Just to clear the issue list I'm closing it, but I keep with my point and I will have much more fun in the future with it.
