### ISSUE TITLE
Interpolation with {js||js} strings doesn't work

### ISSUE THREAD

**Issue by davesnx** [ml-in-barcelona/server-reason-react#120]

**Comment by davesnx** [comment]
`{j||j}`, `{js| |js}` strings could eventually work, but they don't right now so it's better to raise a `[%error]` in the ppx level and wait for the feature to be implemented

Any idea how to support it @pedrobslisboa?

**Comment by anmonteiro** [comment]
https://github.com/ml-in-barcelona/server-reason-react/pull/139 ?

**Comment by davesnx** [comment]
Interpolation don't work

**Comment by davesnx** [comment]
I'm drunk or tired, you are right @anmonteiro both are implemented
