### ISSUE TITLE
Warning: Extra attributes from the server: data-reactroot

### ISSUE THREAD

**Issue by pedrobslisboa** [ml-in-barcelona/server-reason-react#126]
Hey @davesnx, long time no see.

<img width="697" alt="Captura de Tela 2024-04-09 às 18 00 45" src="https://github.com/ml-in-barcelona/server-reason-react/assets/35539594/96a4e853-067f-471e-92da-1c133297b293">

I've noticed that since I updated the server-reason-react to 0.1.0 and using react 18+ I'm having this issue, I believe react 18 removed the `data-reactroot` attribute since I cannot find it on code: https://github.com/search?q=repo%3Afacebook%2Freact+data-reactroot&type=code

Maybe it needs to be removed from the source code?

https://github.com/ml-in-barcelona/server-reason-react/blob/a996cf37685cc9c0c97a36313b79c1ec1fbd1e26/packages/reactDom/src/ReactDOM.ml#L63

I'm solving it by replacing an empty value.

```reason

      Str.global_replace(
        Str.regexp("data-reactroot=\"\""),
        "",
        Str.global_replace(
          Str.regexp("<div id=\"root\"></div>"),
          "<div id=\"root\">" ++ html ++ "</div>",
          indexFileString,
        )
        |> UniversalPortal_Server.appendUniversalPortals(_, portals^),
      )
      |> Dream.html;
```

You can check that on this nextjs 13 with react 18 there is no `data-reactroot`.

https://stackblitz.com/edit/nextjs-d9sshp?file=package.json

**Comment by davesnx** [comment]
data-reactroot attribute (and other html rarities) are added when using `renderToString`, but it isn't when using `renderToStaticMarkup`

Probably you want to us that?

**Comment by davesnx** [comment]
Hey @pedrobslisboa, feel free to join our Discord: https://discord.gg/7pAMMVyUyA

**Comment by davesnx** [comment]
Thank you for fixing and opening the issue 🥇
