### ISSUE TITLE
Set event callbacks running to be browser_only by default.

### ISSUE THREAD

**Issue by pedrobslisboa** [ml-in-barcelona/server-reason-react#162]
The idea is to create a feature that converts all event callbacks into `browser_only`, as events can only be called on a client.

Recently, I created a PR to work on this idea, but I made it a bad idea. Check it out here: https://github.com/ml-in-barcelona/server-reason-react/pull/159#:~:text=Why%20this%20PR%20was%20closed 

I'm opening this issue to discuss how and if it is worth having this feature.

**Comment by davesnx** [comment]
The idea of adding browser_only to all props that start with `on` is probably worth exploring. Do you want to start by re-making the PR and trying to add to all 'onClick' props first?

**Comment by pedrobslisboa** [comment]
@davesnx I was thinking about this: `The idea of adding browser_only to all props that start with on is probably worth exploring`

The `on` prefix is commonly used for HTML event callback, but the user cannot use it like this. So working on this could provide some issues, don't you?

**Comment by jchavarri** [comment]
> I was thinking about this: `The idea of adding browser_only to all props that start with on is probably worth exploring`

How will this solution avoid the issue with unused variable warnings mentioned in #159?

**Comment by jchavarri** [comment]
To my taste, adding `browser_only` to all props starting with `on*` is too much magic happening behind the scenes. I would probably start adding browser_only just on the list of known `on*` props for lower case components, test that solution first, and see how it goes.

**Comment by davesnx** [comment]
Will hold this idea as a won't do for now
