### ISSUE TITLE
jsx error: prop 'playsInline'  isn't valid on a 'video' element - but it should be

### ISSUE THREAD

**Issue by mikaeljan** [ml-in-barcelona/server-reason-react#163]
When setting `playsInline` attribute to a `<video>` tag following error is shown:

`Error: jsx: prop 'playsInline' isn't valid on a 'video' element.`

Sources:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#playsinline
- https://html.spec.whatwg.org/multipage/media.html#htmlvideoelement

**Comment by davesnx** [comment]
This is fixed here https://github.com/ml-in-barcelona/server-reason-react/pull/149, closing.

Could you pin it to the latest main version?
