### ISSUE TITLE
mismatching type for Context

### ISSUE THREAD

**Issue by joprice** [ml-in-barcelona/server-reason-react#28]
The Context module is missing a `type 'a t` as the reason-react context module has, preventing assigning an explicit type that works across the two libs in shared code. I have a fix here, along with a test that compiles a melange and native version of the same file, just to trigger compilation. This would require adding a reason-react test dependency. This branch also has a temporary nix flake, just for my local development purposes, which can be ignored.

https://github.com/ml-in-barcelona/server-reason-react/compare/melange-v2...joprice:server-reason-react:crossTest?expand=1#diff-cadade5b8a347e2aa9719675d7bb80b188df08ecd725c63a5e7c2fe60783ade7

**Comment by davesnx** [comment]
Fixed in #main
