### ISSUE TITLE
Make compatible with latest reason-react

### ISSUE THREAD

**Issue by joprice** [ml-in-barcelona/server-reason-react#46]
The router in server-reason-react is named simply `Router`, whereas the react-react one is `ReasonReactRouter`. This makes it difficult to use in shared code. To work around it locally, you can define a module called `ReasonReactRouter` locally in native that includes `Router`.

**Comment by davesnx** [comment]
This has changed on main under https://github.com/reasonml/reason-react and isn't published yet, so 0.13 is still named ReasonReactRouter.

For now I would recommend do the work around until 0.14 gets published.

**Comment by joprice** [comment]
I just pulled the the unpublished 0.14 changes to try them out. Looks like this repo will need to adopt that wrapping of the library to make things like `ReactDOM` -> `React.DOM` work now.

**Comment by davesnx** [comment]
Yes, we will need to shape the layout

**Comment by davesnx** [comment]
Has been done by https://github.com/ml-in-barcelona/server-reason-react/pull/83
