### ISSUE TITLE
suppress more warnings in browser_only ppx

### ISSUE THREAD

**Issue by joprice** [ml-in-barcelona/server-reason-react#56]
Some warnings are currently suppressed, but in some usages, they still fire, due to either a extra missing warning, the incorrect type for the expression, or not a wide enough location (such as taking the full function definition into account including unused arguments). This prevents enabling strict warnings or requires annotating code to suppress them.

I put up a pr to fix some of them: https://github.com/ml-in-barcelona/server-reason-react/pull/55. 

There is another case that could perhaps be improved, where a hook is defined, but only read from the js side. Perhaps in this case, `let%browser_only` could leave the expression as is and simply add an unused warning suppression instead of failing with `browser only works on expressions or function definitions`.

**Comment by davesnx** [comment]
Can you give an example of the hook example?

**Comment by joprice** [comment]
Sure: Define a `useState` hook. Provide its state as the `value` of an input (which will be used by native on first render). Only use the setter in a browser_only callback like `onClick`, causing native to warn of the setter being unused.

```reason
let (username, setUsername) = React.useSstate(() => "");
...
<input 
  value={username} 
  onClick=[%browser_only { e => setUsername(...)}] />
```

**Comment by davesnx** [comment]
Right, in your example onClick won't be called on the server, so no need to add browser_only.

Allow browser_only to not fail is an interesting idea to supress warnings but unsure how it will look like (maybe adding a warning on the compilation might make more sense than failing at runtime?)

**Comment by joprice** [comment]
Another case I've hit a bit is input params in hooks that use browser_only behavior internally, but provide an immediate result on first render. I modified the ppx to do what I suggested to try it. Here's another example that change works, but I still have to use underscores for parameters to avoid unused warnings:

```reason
let useScrollToEnd = _inputs => {
  let domRef = React.useRef(Js.Nullable.null);
  let%browser_only () =
    React.useEffect1(
      () => {
        ref.current
        |> Js.Nullable.toOption
        |> Option.iter(
             Webapi.Dom.Element.scrollIntoViewWithOptions({
               "behavior": "smooth",
               "block": "end",
             }),
           );
        None;
      },
      _inputs,
    );
  domRef;
};
```

**Comment by davesnx** [comment]
Right... browser_only for effects doesn't feel right. Probably making [%effect] better might make more sense here.

I'm open to discover how it would work and let the user know that there's something broken if you run it on the server (in this case effects won't but other code might)
