### ISSUE TITLE
Implement debugger in melange_native.ppx

### ISSUE THREAD

**Issue by joprice** [ml-in-barcelona/server-reason-react#60]
It would be nice to be able to insert a `[%mel.debugger]` in shared code and have it erased in native code. I'm not that familiar with what ppx operations are possible. Maybe this could be done globally, but it could also be a new extension. Here's a simple attempt at it that works so far:

```ocaml
let debug =
    let extractor = Ast_pattern.(__') in
    let handler ~ctxt:_ { loc } =
      (* TODO: check that no args were provided (PStr with empty structure array?) and error out *)
      match !mode with Js -> [%expr [%mel.debugger]] | Native -> [%expr ()]
    in
    Context_free.Rule.extension
      (Extension.V3.declare "debug" Extension.Context.expression extractor
         handler)
```

**Comment by davesnx** [comment]
I haven't used many debuggers in Melange, but it's a good idea

**Comment by joprice** [comment]
Me neither, but it's a powerful tool when you need it and would be nice to use anywhere without thinking about which context the code is in.

**Comment by davesnx** [comment]
Sounds good to add 👍🏼 

I'm thinking to create a server-reason-react.melange-ppx with all of those, similar to https://github.com/ml-in-barcelona/server-reason-react/issues/37 but keep jsx ppx and melange.ppx split.

**Comment by davesnx** [comment]
Done in 31268b2cdd3d925ce6567575b815416f3edb7889
