### ISSUE TITLE
Cannot run this project in MacOS with Nix

### ISSUE THREAD

**Issue by r17x** [ml-in-barcelona/server-reason-react#97]
### Reproduces

* clone this repository
* run command `nix develop -c $SHELL`
* run command `dune build`
* Error
```
server-reason-react  main via 🐫 v5.1.1+dev0-2023-09-14  ❄️  impure
❯ dune build
File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Location, and its interface was not compiled with -opaque
File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Stdppx, and its interface was not compiled with -opaque
File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Compmisc, and its interface was not compiled with -opaque

File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Location, and its interface was not compiled with -opaque
File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Alcotest_engine__Test, and its interface was not compiled with -opaque

File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Alcotest_engine__Core, and its interface was not compiled with -opaque

File "_none_", line 1:
Error (warning 58 [no-cmx-file]): no cmx file was found in path for module Alcotest_engine__Config, and its interface was not compiled with -opaque

```

Thank you

**Comment by joprice** [comment]
You can modify the dune file to exclude the cmx warning ` (-warn-error +A-d-58 -alert ++browser_only))))`. @davesnx Maybe that can be the default. Not sure if having this warning be promoted to an error is useful.

**Comment by davesnx** [comment]
I don't maintain the nix flake, and I'm unsure how to help here @r17x.

In the opam setup, running `dune build` works fine, you can take a look here: https://github.com/ml-in-barcelona/server-reason-react/actions/runs/6765284900/job/18384737801#step:8:2

**Comment by davesnx** [comment]
But why does even happen? @joprice

**Comment by joprice** [comment]
I spoke to @anmonteiro about this and he said it's due to these repos using `(implicit_transitive_deps false)`. Both Ppxlib and Alcotest set these. I'm not sure if we can modify the nix rules to add the propagated dependencies or if this is something that just has to be treated as an ignorable warning.

**Comment by davesnx** [comment]
Right, if you want to build this locally with nix you might need to fix ppxlib and alcotest, or disable the warning. 

There's no code change related with server-reason-react, so I will close this
